### PR TITLE
optimized sub-optimal code.

### PR DESCRIPTION
**Pull request by ghost**
Made the following changes:

-> optimized conditional statements.
-> added Exception in exceptional statement as it's too broad.
-> optimized dictionary declarations.

### CODE REVIEW

**Comment by palewire** [comment]
What happens in cases where a value isn't found? Don't we need those if statements for those circumstances?

**Comment by ghost** [comment]
There are very less chances that such a situation might occur in the code even though external files such as 'metar (lastest.json)' & 'aq (aqi.json)' can be a possible reason for an error in case the data is manipulated or not found. Internally, it's all fine.

Talking of the if statements, they were a major threat to the performance of the program and even if the data/value was not found, even they will raise a KeyError.

So, the program stands at the same position on which it was before just that it's more optimized now.

**Comment by palewire** [comment]
My judgement is that the threat of a bad or null value, which could lead to a crash or incorrect information being published, is greater than the small performance differences, which I suspect are a very small fraction of a second.

**Comment by ghost** [comment]
But this program is still going to fetch the wrong information in the case of the if-else blocks or let it crash if one of them is not found or manipulated.

Overall, as I said before, the changes are only related to performance, any error that exists after the changes made is also going to be raised without the changes as neither there were any special conditions for such situations before nor there are now.

So, one of the only ways you can tackle is by defining some extra try-except blocks or adding some if-else for resisting such errors even in the present code.

Talking about the changes, they make it even easier for you to define such conditions as rather enclosing the whole if-else blocks in another conditional statement, you just have to enclose the statement retrieving the data from the mapping making it both error prone and performance friendly.

**Pull request closed without merging**
